# Travis-CI Build for RfidResearchGroup/Proxmark3
language: c

#default linux build env is: xenial
compiler: gcc

# Test on Linux and MacOS
matrix:
  include:
    - os: osx
      osx_image: xcode9.2   # OS X 10.13
    - os: linux
      dist: xenial
      sudo: required

before_install:
## Install ARM toolchain on Linux.
## add our homebrew tap for MacOS
## Note: all dependencies on MacOS should be resolved by the brew install command
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
    sudo apt-get update -qq;
    sudo apt-get install -y gcc-arm-none-eabi libnewlib-dev;
  elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew update;
    brew tap RfidResearchGroup/proxmark3;
  fi

install:
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
    brew info proxmark3;
    brew options proxmark3;	
    brew install --HEAD proxmark3;
  elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
    make all;
  fi

before_script:

script: 
## start and run a test script
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
    proxmark3 -h ;
  elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
    ./client/proxmark3 -h ;
  fi